# Generated by Django 3.0.7 on 2020-09-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_price', models.IntegerField(max_length=4)),
                ('image', models.ImageField(upload_to='media/images')),
                ('home_display', models.BooleanField(default=False)),
                ('offer_price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Product list',
            },
        ),
    ]
